name: Build and deploy Python app to Azure Web App - calotrack-backend

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'calotrack-backend' 
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_040C... }} # JANGAN UBAH BAGIAN INI
